name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Adicione aqui comandos de build/teste para Node.js se necess√°rio

      - name: Install dependencies
        working-directory: upload-lambda/src/main
        run: pip install

      - name: Zip Lambda function
        working-directory: upload-lambda/src/main
        run: |
          zip -r upload-lambda.zip .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Confirm AWS caller identity
        run: |
          echo "Checking AWS caller identity"
          aws sts get-caller-identity

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Delete existing Lambda (if exists)
        run: |
          aws lambda delete-function --function-name authorization_lambda || echo "Lambda not found, continuing"
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
